[package]
name = "selene-core"
version = "0.3.1"
edition = "2024"
rust-version = "1.94"
authors = ["Jake Arkinstall <jake.arkinstall@quantinuum.com>"]
description = "Core interoperability and plugin interfaces for the Selene quantum emulator"
readme = "README.md"
repository = "https://github.com/quantinuum/selene"
homepage = "https://github.com/quantinuum/selene"
documentation = "https://docs.rs/selene-core"
license = "Apache-2.0"
keywords = ["quantum", "emulator", "simulation", "plugins"]
categories = ["science", "simulation"]

[lib]
name = "selene_core"
path = "rust/lib.rs"
crate-type = ["lib"]

[dependencies]
anyhow = "1.0"
thiserror = "2.0"
libloading = "0.8"
delegate = "0.13"
derive_more = { version = "2.1", features = ["from", "into", "add", "add_assign"] }

[lints.clippy]
undocumented_unsafe_blocks = "allow" # TODO: add safety docs
missing_safety_doc = "allow"         # TODO: add safety docs
