[package]
name = "selene-core"
version = "1.0.0-alpha.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "Core Rust APIs for Quantinuum's Selene plugins, gate apis, and simulation infrastructure."
readme = "README.md"
homepage = "https://github.com/quantinuum/selene"
documentation = "https://docs.rs/selene-core"
keywords = [
    "Quantum",
    "Quantinuum",
    "Simulation",
    "Selene",
]
categories = [
    "science:quantum-computing",
    "emulators",
    "simulation",
    "api-bindings",
    "development-tools:ffi",
]
include = [
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "rust/**/*.rs",
    "rust/**/README.md",
]

[lib]
name = "selene_core"
path = "rust/lib.rs"
crate-type = ["lib"]

[dependencies]
anyhow = "1.0"
thiserror = "2.0"
libloading = "0.8"
delegate = "0.13"
derive_more = { version = "2.1", features = ["full"] }
bitflags = "2"
blake3 = "1"
indexmap = "2"
smallvec = "1"
static_assertions = "1"

[lints.clippy]
undocumented_unsafe_blocks = "allow"
missing_safety_doc = "allow"
