[package]
name = "selene-v02-compat-runtime"
version = "0.3.0-alpha.1"
edition = "2024"

[workspace]

[lib]
name = "selene_v02_compat_runtime"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
libloading = "0.8"
selene-core = { path = "../../../selene-core" }
selene-v02-compat-common = { path = "../v02-common" }

[lints.clippy]
undocumented_unsafe_blocks = "allow"
missing_safety_doc = "allow"
