; In this example of using QIS directly, we perform a simple
; addition of two 4-bit numbers (3 and 11) with carry, storing the
; result in the RHS and a carry. We output the answer as an integer.


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;  QIS function declarations   ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

declare void @setup(i64) local_unnamed_addr
declare i64 @teardown() local_unnamed_addr

declare i64 @___qalloc() local_unnamed_addr
declare void @___reset(i64) local_unnamed_addr
declare void @___qfree(i64) local_unnamed_addr
declare void @___rp(i64, double, double) local_unnamed_addr
declare void @___rpp(i64, i64, double, double) local_unnamed_addr
declare void @___rz(i64, double) local_unnamed_addr
declare i64 @___lazy_measure(i64) local_unnamed_addr

declare void @___dec_future_refcount(i64) local_unnamed_addr
declare void @print_int(i8*, i64, i64) local_unnamed_addr
declare i1 @___read_future_bool(i64) local_unnamed_addr

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; constants for readability

@zero = constant double 0x0000000000000000
@pi = constant double 0x400921fb54442d18
@half_pi = constant double 0x3ff921fb54442d18
@minus_half_pi = constant double 0xbff921fb54442d18
@quarter_pi = constant double 0x3fe921fb54442d18
@minus_quarter_pi = constant double 0xbfe921fb54442d18

; our strings are prefixed with a single-byte length
; the length of "USER:INT:answer" is 15 (0x0F)

@result_tag = private constant [16 x i8] c"\0FUSER:INT:answer"

define i64 @qmain(i64 %0) local_unnamed_addr {
entry:
    %zero = load double, ptr @zero
    %pi = load double, ptr @pi
    %half_pi = load double, ptr @half_pi
    %minus_half_pi = load double, ptr @minus_half_pi
    %quarter_pi = load double, ptr @quarter_pi
    %minus_quarter_pi = load double, ptr @minus_quarter_pi


    tail call void @setup(i64 %0)

    ; allocate 10 qubits

    %lhs_0 = tail call i64 @___qalloc()
    %lhs_1 = tail call i64 @___qalloc()
    %lhs_2 = tail call i64 @___qalloc()
    %lhs_3 = tail call i64 @___qalloc()
    %rhs_0 = tail call i64 @___qalloc()
    %rhs_1 = tail call i64 @___qalloc()
    %rhs_2 = tail call i64 @___qalloc()
    %rhs_3 = tail call i64 @___qalloc()
    %carry = tail call i64 @___qalloc()
    %ancilla = tail call i64 @___qalloc()

    ; reset them all to |0>

    tail call void @___reset(i64 %lhs_0)
    tail call void @___reset(i64 %lhs_1)
    tail call void @___reset(i64 %lhs_2)
    tail call void @___reset(i64 %lhs_3)
    tail call void @___reset(i64 %rhs_0)
    tail call void @___reset(i64 %rhs_1)
    tail call void @___reset(i64 %rhs_2)
    tail call void @___reset(i64 %rhs_3)
    tail call void @___reset(i64 %carry)
    tail call void @___reset(i64 %ancilla)

    ; lhs = 3 = 0b011 
    tail call void @___rp(i64 %lhs_0, double %pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %pi, double %zero)
    ; rhs = 11 = 0b1011
    tail call void @___rp(i64 %rhs_0, double %pi, double %zero)
    tail call void @___rp(i64 %rhs_1, double %pi, double %zero)
    tail call void @___rp(i64 %rhs_3, double %pi, double %zero)

    ; perform addition with carry, storing result in lhs and carry in carry

    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %rhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_2, i64 %rhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_3, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_3, i64 %rhs_3, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_3, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_3, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_3, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %ancilla, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_2, i64 %lhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %ancilla, double %pi)
    tail call void @___rp(i64 %lhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_0, i64 %ancilla, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %ancilla, double %minus_quarter_pi)
    tail call void @___rp(i64 %rhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_0, i64 %ancilla, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %ancilla, double %quarter_pi)
    tail call void @___rp(i64 %lhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_0, i64 %ancilla, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %ancilla, double %minus_quarter_pi)
    tail call void @___rp(i64 %rhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_0, i64 %ancilla, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %ancilla, double %quarter_pi)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %ancilla, double %pi)
    tail call void @___rz(i64 %lhs_0, double %quarter_pi)
    tail call void @___rp(i64 %rhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_0, i64 %lhs_0, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_0, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_0, double %minus_quarter_pi)
    tail call void @___rz(i64 %rhs_0, double %quarter_pi)
    tail call void @___rp(i64 %rhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_0, i64 %lhs_0, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_0, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_3, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_3, i64 %lhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_3, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_3, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %lhs_1, double %pi)
    tail call void @___rp(i64 %rhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_1, i64 %lhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_1, double %minus_quarter_pi)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %ancilla, i64 %lhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %ancilla, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_1, double %quarter_pi)
    tail call void @___rp(i64 %rhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_1, i64 %lhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_1, double %minus_quarter_pi)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %ancilla, i64 %lhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %ancilla, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_1, double %quarter_pi)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %lhs_1, double %pi)
    tail call void @___rz(i64 %rhs_1, double %quarter_pi)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %ancilla, i64 %rhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %ancilla, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %rhs_1, double %minus_quarter_pi)
    tail call void @___rz(i64 %ancilla, double %quarter_pi)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %ancilla, i64 %rhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %ancilla, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_3, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_3, i64 %carry, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_3, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_3, double %minus_half_pi)
    tail call void @___rp(i64 %carry, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %lhs_2, double %pi)
    tail call void @___rp(i64 %rhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_2, i64 %lhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_2, double %minus_quarter_pi)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %lhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_2, double %quarter_pi)
    tail call void @___rp(i64 %rhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_2, i64 %lhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_2, double %minus_quarter_pi)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %lhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_2, double %quarter_pi)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %lhs_2, double %pi)
    tail call void @___rz(i64 %rhs_2, double %quarter_pi)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %rhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %rhs_2, double %minus_quarter_pi)
    tail call void @___rz(i64 %lhs_1, double %quarter_pi)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %rhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %rhs_1, double %pi, double %zero)
    tail call void @___rp(i64 %rhs_2, double %pi, double %zero)
    tail call void @___rp(i64 %carry, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %carry, double %pi)
    tail call void @___rp(i64 %rhs_3, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_3, i64 %carry, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_3, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_3, double %minus_half_pi)
    tail call void @___rp(i64 %carry, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %carry, double %minus_quarter_pi)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_2, i64 %carry, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %carry, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %carry, double %quarter_pi)
    tail call void @___rp(i64 %rhs_3, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_3, i64 %carry, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_3, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_3, double %minus_half_pi)
    tail call void @___rp(i64 %carry, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %carry, double %minus_quarter_pi)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_2, i64 %carry, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %carry, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %carry, double %quarter_pi)
    tail call void @___rp(i64 %carry, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %carry, double %pi)
    tail call void @___rz(i64 %rhs_3, double %quarter_pi)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_2, i64 %rhs_3, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_3, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %rhs_3, double %minus_quarter_pi)
    tail call void @___rz(i64 %lhs_2, double %quarter_pi)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_2, i64 %rhs_3, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_3, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %ancilla, i64 %rhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %ancilla, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %rhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_2, i64 %rhs_3, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_3, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %lhs_2, double %pi)
    tail call void @___rp(i64 %rhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_2, i64 %lhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_2, double %minus_quarter_pi)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %lhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_2, double %quarter_pi)
    tail call void @___rp(i64 %rhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_2, i64 %lhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_2, double %minus_quarter_pi)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %lhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_2, double %quarter_pi)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %lhs_2, double %pi)
    tail call void @___rz(i64 %rhs_2, double %quarter_pi)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %rhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %rhs_2, double %minus_quarter_pi)
    tail call void @___rz(i64 %lhs_1, double %quarter_pi)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %rhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_3, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_3, i64 %lhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_3, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_3, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %rhs_2, double %pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %lhs_1, double %pi)
    tail call void @___rp(i64 %rhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_1, i64 %lhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_1, double %minus_quarter_pi)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %ancilla, i64 %lhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %ancilla, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_1, double %quarter_pi)
    tail call void @___rp(i64 %rhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_1, i64 %lhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_1, double %minus_quarter_pi)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %ancilla, i64 %lhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %ancilla, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_1, double %quarter_pi)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %lhs_1, double %pi)
    tail call void @___rz(i64 %rhs_1, double %quarter_pi)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %ancilla, i64 %rhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %ancilla, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %rhs_1, double %minus_quarter_pi)
    tail call void @___rz(i64 %ancilla, double %quarter_pi)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %ancilla, i64 %rhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %ancilla, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_2, i64 %lhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %rhs_1, double %pi, double %zero)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %ancilla, double %pi)
    tail call void @___rp(i64 %lhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_0, i64 %ancilla, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %ancilla, double %minus_quarter_pi)
    tail call void @___rp(i64 %rhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_0, i64 %ancilla, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %ancilla, double %quarter_pi)
    tail call void @___rp(i64 %lhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_0, i64 %ancilla, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %ancilla, double %minus_quarter_pi)
    tail call void @___rp(i64 %rhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_0, i64 %ancilla, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %ancilla, double %quarter_pi)
    tail call void @___rp(i64 %ancilla, double %half_pi, double %minus_half_pi)
    tail call void @___rz(i64 %ancilla, double %pi)
    tail call void @___rz(i64 %lhs_0, double %quarter_pi)
    tail call void @___rp(i64 %rhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_0, i64 %lhs_0, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_0, double %minus_half_pi, double %zero)
    tail call void @___rz(i64 %lhs_0, double %minus_quarter_pi)
    tail call void @___rz(i64 %rhs_0, double %quarter_pi)
    tail call void @___rp(i64 %rhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %rhs_0, i64 %lhs_0, double %half_pi, double %zero)
    tail call void @___rp(i64 %rhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %rhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %lhs_0, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %ancilla, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %ancilla, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_0, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_0, i64 %rhs_0, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_0, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_0, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_0, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_1, i64 %rhs_1, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_1, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_1, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_1, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_2, i64 %rhs_2, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_2, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_2, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_2, double %minus_half_pi, double %zero)
    tail call void @___rp(i64 %lhs_3, double %half_pi, double %half_pi)
    tail call void @___rpp(i64 %lhs_3, i64 %rhs_3, double %half_pi, double %zero)
    tail call void @___rp(i64 %lhs_3, double %minus_half_pi, double %half_pi)
    tail call void @___rz(i64 %lhs_3, double %minus_half_pi)
    tail call void @___rp(i64 %rhs_3, double %minus_half_pi, double %zero)

    ; allocate 4 int64s for measurement handles
    %ref_0 = tail call i64 @___lazy_measure(i64 %rhs_0)
    %ref_1 = tail call i64 @___lazy_measure(i64 %rhs_1)
    %ref_2 = tail call i64 @___lazy_measure(i64 %rhs_2)
    %ref_3 = tail call i64 @___lazy_measure(i64 %rhs_3)
    %ref_4 = tail call i64 @___lazy_measure(i64 %carry)

    ; read them back as booleans
    %ans_0 = tail call i1 @___read_future_bool(i64 %ref_0)
    %ans_1 = tail call i1 @___read_future_bool(i64 %ref_1)
    %ans_2 = tail call i1 @___read_future_bool(i64 %ref_2)
    %ans_3 = tail call i1 @___read_future_bool(i64 %ref_3)
    %ans_4 = tail call i1 @___read_future_bool(i64 %ref_4)


    ; decrement future reference counts
    tail call void @___dec_future_refcount(i64 %ref_0)
    tail call void @___dec_future_refcount(i64 %ref_1)
    tail call void @___dec_future_refcount(i64 %ref_2)
    tail call void @___dec_future_refcount(i64 %ref_3)
    tail call void @___dec_future_refcount(i64 %ref_4)

    ; free all qubits
    tail call void @___qfree(i64 %lhs_0)
    tail call void @___qfree(i64 %lhs_1)
    tail call void @___qfree(i64 %lhs_2)
    tail call void @___qfree(i64 %lhs_3)
    tail call void @___qfree(i64 %rhs_0)
    tail call void @___qfree(i64 %rhs_1)
    tail call void @___qfree(i64 %rhs_2)
    tail call void @___qfree(i64 %rhs_3)
    tail call void @___qfree(i64 %carry)
    tail call void @___qfree(i64 %ancilla)

    ; combine the answer bits into a single integer using llvm intrinsics
    %bit0 = zext i1 %ans_0 to i64
    %bit1 = zext i1 %ans_1 to i64
    %bit2 = zext i1 %ans_2 to i64
    %bit3 = zext i1 %ans_3 to i64
    %bit4 = zext i1 %ans_4 to i64

    %bit1_shifted = shl i64 %bit1, 1
    %bit2_shifted = shl i64 %bit2, 2
    %bit3_shifted = shl i64 %bit3, 3
    %bit4_shifted = shl i64 %bit4, 4

    %tmp0 = or i64 %bit0, %bit1_shifted
    %tmp1 = or i64 %tmp0, %bit2_shifted
    %tmp2 = or i64 %tmp1, %bit3_shifted
    %answer = or i64 %tmp2, %bit4_shifted

    tail call void @print_int(i8* getelementptr inbounds ([16 x i8], [16 x i8]* @result_tag, i64 0, i64 0), i64 15, i64 %answer)
    %status = tail call i64 @teardown()
    ret i64 %status
}

!name = !{!0}

!0 = !{!"mainlib"}
