[package]
name = "selene-simulator-quest"
version.workspace = true
edition.workspace = true

[lib]
name = "selene_quest_plugin"
path = "rust/lib.rs"
doctest = false
crate-type = ["cdylib"]

[build-dependencies]
cmake = "0.1"

[dependencies]
anyhow = { workspace = true }
selene-core = { path = "../../../selene-core" }
sysinfo = { version = "0.35" }
bytesize = { version = "2.3" }

[lints]
workspace = true
