from itertools import product
from tqdm import tqdm
from pytket import Circuit
from pytket.passes import GreedyPauliSimp, SynthesiseTket


def simplify(circuit: Circuit) -> Circuit:
    """Simplify a circuit by applying the GreedyPauliSimp pass."""
    pass1_ = SynthesiseTket()
    pass2_ = GreedyPauliSimp(allow_zzphase=True, trials=10)
    newcirc = circuit.copy()
    pass1_.apply(newcirc)
    pass2_.apply(newcirc)
    if repr(newcirc) == repr(circuit):
        return None
    for command in newcirc.get_commands():
        if not command.op.is_clifford():
            return None
    return newcirc


def rz_gate(theta):
    circ = Circuit(1)
    circ.Rz(theta, 0)
    return circ


def rxy_gate(theta, phi):
    circ = Circuit(1)
    circ.PhasedX(theta, phi, 0)
    return circ


def rzz_gate(theta):
    circ = Circuit(2)
    circ.ZZPhase(theta, 0, 1)
    return circ


def analyse_span(name, gate, start_angle, end_angle, num_points, dim=1):
    """Return a list of gates for a range of angles where a clifford sequence is found."""
    print(f"-------------- {name} --------------")

    angles = [
        start_angle + i * (end_angle - start_angle) / num_points
        for i in range(num_points)
    ]
    result = {}  # map from simplified circuit to list of angles that simplify to it.
    for angles in tqdm(product(angles, repeat=dim), total=len(angles) ** dim):
        original = gate(*angles)
        simplified = simplify(original)
        if simplified is not None:
            if repr(simplified) not in result:
                result[repr(simplified)] = []
            result[repr(simplified)].append(tuple(angles))

    for simplified, angles_list in result.items():
        print("-------------------------")
        print(f"Circuit: {simplified}")
        print("Generated by angles:")
        for a in angles_list:
            print(f"  {a} pi")

    print("====================================")


if __name__ == "__main__":
    analyse_span("rz", rz_gate, 0, 2, 16)
    analyse_span("rxy", rxy_gate, 0, 2, 16, dim=2)
    analyse_span("rzz", rzz_gate, 0, 2, 16, dim=1)
