language = "C"

include_version = false
includes = ["selene/core_types.h"]
no_includes = false
cpp_compat = true
after_includes = ""
braces = "SameLine"
line_length = 100
tab_width = 2
documentation = true
documentation_style = "auto"
documentation_length = "full"
line_endings = "LF"
style = "both"
sort_by = "None"
usize_is_size_t = true

[export]
include = [
  "ErrorModelAPIVersion",
  "ErrorModelInstance",
  "ErrorModelSetResultInterface",
  "ErrorModelSetResultInstance",
  "ErrorModelPluginDescriptorV1",
  "RuntimeGetOperationInstance",
  "RuntimeExtractOperationInterface",
  "RuntimeExtractOperationInstance",
  "SimulatorInstance",
  "SimulatorOperationInterface",
  "Errno",
]
item_types = ["functions", "structs", "opaque", "enums", "typedefs"]
renaming_overrides_prefixing = false

[export.rename]
"ErrorModelAPIVersion" = "SeleneErrorModelAPIVersion"
"ErrorModelInstance" = "SeleneErrorModelInstance"
"ErrorModelSetResultInterface" = "SeleneErrorModelSetResultInterface"
"ErrorModelSetResultInstance" = "SeleneErrorModelSetResultInstance"
"ErrorModelPluginDescriptorV1" = "SeleneErrorModelPluginDescriptorV1"
"RuntimeGetOperationInstance" = "SeleneRuntimeGetOperationInstance"
"RuntimeExtractOperationInterface" = "SeleneRuntimeExtractOperationInterface"
"RuntimeExtractOperationInstance" = "SeleneRuntimeExtractOperationInstance"
"SimulatorInstance" = "SeleneSimulatorInstance"
"Errno" = "SeleneErrno"
"CURRENT_API_VERSION" = "SELENE_ERROR_MODEL_CURRENT_API_VERSION"

[export.mangle]
rename_types = "SnakeCase"

[fn]
rename_args = "None"
args = "vertical"

[enum]
rename_variants = "None"
add_sentinel = false
prefix_with_name = false
derive_helper_methods = false
derive_const_casts = false
derive_mut_casts = false
derive_tagged_enum_destructor = false
derive_tagged_enum_copy_constructor = false
enum_class = true
private_default_tagged_enum_constructor = false

[const]
allow_static_const = true
allow_constexpr = false
