#ifndef SELENE_CORE_TYPES_H
#define SELENE_CORE_TYPES_H

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef struct Operation Operation;

typedef int32_t SeleneErrno;

#endif  /* SELENE_CORE_TYPES_H */
