#ifndef SELENE_ERROR_MODEL_H
#define SELENE_ERROR_MODEL_H

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "selene/core_types.h"
#include "selene/runtime.h"
/**
 * An error-model plugin must export either this descriptor symbol or the accessor below.
 * The accessor form is recommended for portable C and C++ plugins.
 */
struct SeleneErrorModelPluginDescriptorV1;
#ifdef __cplusplus
extern "C" {
#endif
extern const struct SeleneErrorModelPluginDescriptorV1 selene_error_model_plugin_descriptor_v1;
const struct SeleneErrorModelPluginDescriptorV1 *selene_error_model_get_plugin_descriptor_v1(void);
#ifdef __cplusplus
}
#endif


/**
 * The current error-model plugin API version, packed for the C descriptor ABI.
 */
#define SELENE_ERROR_MODEL_CURRENT_API_VERSION 768

/**
 * A decomposed error-model API version.
 *
 * Plugin descriptors use the packed `SELENE_ERROR_MODEL_CURRENT_API_VERSION`
 * integer rather than this structure.
 */
typedef struct SeleneErrorModelAPIVersion {
  /**
   * Reserved for future use, must be 0.
   */
  uint8_t reserved;
  /**
   * Major version of the API.
   */
  uint8_t major;
  /**
   * Minor version of the API.
   */
  uint8_t minor;
  /**
   * Patch version of the API.
   */
  uint8_t patch;
} SeleneErrorModelAPIVersion;

typedef void *SeleneErrorModelInstance;

/**
 * An instance is provided to `selene_runtime_get_next_operations`, which must
 * pass that back to any function it calls in it's provided
 * [ErrorModelSetResultInterface].
 */
typedef void *SeleneErrorModelSetResultInstance;

/**
 * A plugin's implementation of `selene_runtime_get_next_operations` is provided
 * a pointer to a `ErrorModelSetResultInterface` as well as a
 * [ErrorModelSetResultInstance]. It should call the functions
 * within to populate a batch. All such calls must pass the instance as the
 * first parameter.
 */
typedef struct SeleneErrorModelSetResultInterface {
  void (*set_bool_result_fn)(SeleneErrorModelSetResultInstance,
                             uint64_t,
                             bool);
  void (*set_u64_result_fn)(SeleneErrorModelSetResultInstance,
                            uint64_t,
                            uint64_t);
} SeleneErrorModelSetResultInterface;

typedef void *SeleneSimulatorInstance;

typedef struct SimulatorOperationInterface {
  SeleneErrno (*exit_fn)(SeleneSimulatorInstance instance);
  SeleneErrno (*shot_start_fn)(SeleneSimulatorInstance instance,
                               uint64_t shot_id,
                               uint64_t seed);
  SeleneErrno (*shot_end_fn)(SeleneSimulatorInstance instance);
  SeleneErrno (*rxy_fn)(SeleneSimulatorInstance instance,
                        uint64_t qubit,
                        double theta,
                        double phi);
  SeleneErrno (*rz_fn)(SeleneSimulatorInstance instance,
                       uint64_t qubit,
                       double theta);
  SeleneErrno (*rzz_fn)(SeleneSimulatorInstance instance,
                        uint64_t qubit1,
                        uint64_t qubit2,
                        double theta);
  SeleneErrno (*rpp_fn)(SeleneSimulatorInstance instance,
                        uint64_t qubit1,
                        uint64_t qubit2,
                        double theta,
                        double phi);
  SeleneErrno (*measure_fn)(SeleneSimulatorInstance instance,
                            uint64_t qubit);
  SeleneErrno (*postselect_fn)(SeleneSimulatorInstance instance,
                               uint64_t qubit,
                               bool target_value);
  SeleneErrno (*reset_fn)(SeleneSimulatorInstance instance,
                          uint64_t qubit);
  SeleneErrno (*get_metric_fn)(SeleneSimulatorInstance instance,
                               uint8_t nth_metric,
                               char *tag_ptr,
                               uint8_t *datatype_ptr,
                               uint64_t *data_ptr);
  SeleneErrno (*dump_state_fn)(SeleneSimulatorInstance instance,
                               const char *file,
                               const uint64_t *qubits,
                               uint64_t n_qubits);
} SimulatorOperationInterface;

typedef struct SimulatorHandle {
  SeleneSimulatorInstance instance;
  struct SimulatorOperationInterface interface;
} SimulatorHandle;

typedef struct ErrorModelSetResultHandle {
  SeleneErrorModelSetResultInstance instance;
  struct SeleneErrorModelSetResultInterface interface;
} ErrorModelSetResultHandle;

/**
 * The C ABI descriptor exported by an error-model plugin.
 *
 * Function pointer fields documented as optional may be null. All other
 * function pointer fields must be populated.
 */
typedef struct SeleneErrorModelPluginDescriptorV1 {
  /**
   * Must be `sizeof(SeleneErrorModelPluginDescriptorV1)`.
   */
  uint64_t struct_size;
  /**
   * Must be `SELENE_ERROR_MODEL_CURRENT_API_VERSION`.
   */
  uint64_t api_version;
  SeleneErrno (*init_fn)(SeleneErrorModelInstance *handle,
                         uint64_t n_qubits,
                         uint32_t error_model_argc,
                         const char *const *error_model_argv);
  /**
   * Optional. If null, no plugin-specific cleanup is performed.
   */
  SeleneErrno (*exit_fn)(SeleneErrorModelInstance handle);
  SeleneErrno (*shot_start_fn)(SeleneErrorModelInstance handle,
                               uint64_t shot_id,
                               uint64_t error_model_seed);
  SeleneErrno (*shot_end_fn)(SeleneErrorModelInstance handle);
  SeleneErrno (*handle_operations_fn)(SeleneErrorModelInstance handle,
                                      RuntimeExtractOperationHandle batch,
                                      struct SimulatorHandle simulator,
                                      struct ErrorModelSetResultHandle result);
  /**
   * Optional. A null pointer means the plugin exposes no metrics.
   */
  SeleneErrno (*get_metrics_fn)(SeleneErrorModelInstance handle,
                                uint8_t nth_metric,
                                char *out_tag_str,
                                uint8_t *out_datatype,
                                uint64_t *out_data);
} SeleneErrorModelPluginDescriptorV1;

#endif  /* SELENE_ERROR_MODEL_H */
