#ifndef SELENE_SIMULATOR_H
#define SELENE_SIMULATOR_H

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "selene/core_types.h"
/**
 * A simulator plugin must export either this descriptor symbol or the accessor below.
 * The accessor form is recommended for portable C and C++ plugins.
 */
struct SeleneSimulatorPluginDescriptorV1;
#ifdef __cplusplus
extern "C" {
#endif
extern const struct SeleneSimulatorPluginDescriptorV1 selene_simulator_plugin_descriptor_v1;
const struct SeleneSimulatorPluginDescriptorV1 *selene_simulator_get_plugin_descriptor_v1(void);
#ifdef __cplusplus
}
#endif


/**
 * The current simulator plugin API version, packed for the C descriptor ABI.
 */
#define SELENE_SIMULATOR_CURRENT_API_VERSION 257

/**
 * A decomposed simulator API version.
 *
 * Plugin descriptors use the packed `SELENE_SIMULATOR_CURRENT_API_VERSION`
 * integer rather than this structure.
 */
typedef struct SeleneSimulatorAPIVersion {
  /**
   * Reserved for future use, must be 0.
   */
  uint8_t reserved;
  /**
   * Major version of the API.
   */
  uint8_t major;
  /**
   * Minor version of the API.
   */
  uint8_t minor;
  /**
   * Patch version of the API.
   */
  uint8_t patch;
} SeleneSimulatorAPIVersion;

typedef void *SeleneSimulatorInstance;

/**
 * The C ABI descriptor exported by a simulator plugin.
 *
 * Function pointer fields documented as optional may be null. All other
 * function pointer fields must be populated.
 */
typedef struct SeleneSimulatorPluginDescriptorV1 {
  /**
   * Must be `sizeof(SeleneSimulatorPluginDescriptorV1)`.
   */
  uint64_t struct_size;
  /**
   * Must be `SELENE_SIMULATOR_CURRENT_API_VERSION`.
   */
  uint64_t api_version;
  /**
   * Optional. Returns a static, null-terminated plugin name.
   */
  const char *(*get_name_fn)(void);
  SeleneErrno (*init_fn)(SeleneSimulatorInstance *handle,
                         uint64_t n_qubits,
                         uint32_t argc,
                         const char *const *argv);
  /**
   * Optional. If null, no plugin-specific cleanup is performed.
   */
  SeleneErrno (*exit_fn)(SeleneSimulatorInstance handle);
  SeleneErrno (*shot_start_fn)(SeleneSimulatorInstance handle,
                               uint64_t shot_id,
                               uint64_t seed);
  SeleneErrno (*shot_end_fn)(SeleneSimulatorInstance handle);
  /**
   * Optional. A null pointer means the operation is unsupported.
   */
  SeleneErrno (*rxy_fn)(SeleneSimulatorInstance handle,
                        uint64_t qubit,
                        double theta,
                        double phi);
  /**
   * Optional. A null pointer means the operation is unsupported.
   */
  SeleneErrno (*rz_fn)(SeleneSimulatorInstance handle,
                       uint64_t qubit0,
                       double theta);
  /**
   * Optional. A null pointer means the operation is unsupported.
   */
  SeleneErrno (*rzz_fn)(SeleneSimulatorInstance handle,
                        uint64_t qubit0,
                        uint64_t qubit1,
                        double theta);
  /**
   * Optional. A null pointer means the operation is unsupported.
   */
  SeleneErrno (*rpp_fn)(SeleneSimulatorInstance handle,
                        uint64_t qubit0,
                        uint64_t qubit1,
                        double theta,
                        double phi);
  SeleneErrno (*measure_fn)(SeleneSimulatorInstance handle,
                            uint64_t qubit);
  /**
   * Optional. A null pointer means postselection is unsupported.
   */
  SeleneErrno (*postselect_fn)(SeleneSimulatorInstance handle,
                               uint64_t qubit,
                               bool target_value);
  SeleneErrno (*reset_fn)(SeleneSimulatorInstance handle,
                          uint64_t qubit);
  /**
   * Optional. A null pointer means the plugin exposes no metrics.
   */
  SeleneErrno (*get_metrics_fn)(SeleneSimulatorInstance handle,
                                uint8_t nth_metric,
                                char *tag_out,
                                uint8_t *datatype_out,
                                uint64_t *value_out);
  SeleneErrno (*dump_state_fn)(SeleneSimulatorInstance handle,
                               const char *file,
                               const uint64_t *qubits,
                               uint64_t n_qubits);
} SeleneSimulatorPluginDescriptorV1;

#endif  /* SELENE_SIMULATOR_H */
