"""Shared test fixtures and helpers for selene-sim tests."""

import platform
from pathlib import Path

import pytest

_TESTS_DIR = Path(__file__).parent
_QIS_DIR = _TESTS_DIR / "resources" / "qis" / "guppy"
_HUGR_DIR = _TESTS_DIR / "resources" / "hugr"


def get_platform_suffix() -> str:
    """Return the platform-specific suffix used in QIS file names."""
    arch = platform.machine().lower()
    system = platform.system().lower()
    match arch:
        case "arm64" | "aarch64":
            target_arch = "aarch64"
        case "amd64" | "x86_64":
            target_arch = "x86_64"
        case _:
            raise RuntimeError(f"Unsupported architecture: {arch}")
    match system:
        case "linux":
            target_system = "unknown-linux-gnu"
        case "darwin":
            target_system = "apple-darwin"
        case "windows":
            target_system = "windows-msvc"
        case _:
            raise RuntimeError(f"Unsupported OS: {system}")
    return f"{target_arch}-{target_system}"


_PLATFORM_SUFFIX = get_platform_suffix()


def qis_file(name: str) -> Path:
    """Return the path to a pre-compiled QIS LLVM IR file.

    The file must have been generated by running:
        uv run selene-sim/python/tests/scripts/compile_guppy_programs.py
    or equivalently:
        just generate-qis
    """
    path = _QIS_DIR / f"{name}-{_PLATFORM_SUFFIX}.ll"
    if not path.exists():
        pytest.skip(
            f"QIS file not found: {path}\n"
            "Run 'just generate-qis' to compile guppy programs to QIS snapshots."
        )
    return path


def hugr_file(name: str) -> Path:
    """Return the path to a pre-compiled HUGR envelope file.

    HUGR files are platform-independent and can be used with any build method.
    """
    path = _HUGR_DIR / f"{name}.hugr"
    if not path.exists():
        pytest.skip(
            f"HUGR file not found: {path}\n"
            "Run 'just generate-qis' to compile guppy programs to HUGR snapshots."
        )
    return path
