#ifndef SELENE_RUNTIME_H
#define SELENE_RUNTIME_H

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "selene/core_types.h"
/**
 * A runtime plugin must export either this descriptor symbol or the accessor below.
 * The accessor form is recommended for portable C and C++ plugins.
 */
struct SeleneRuntimePluginDescriptorV1;
#ifdef __cplusplus
extern "C" {
#endif
extern const struct SeleneRuntimePluginDescriptorV1 selene_runtime_plugin_descriptor_v1;
const struct SeleneRuntimePluginDescriptorV1 *selene_runtime_get_plugin_descriptor_v1(void);
#ifdef __cplusplus
}
#endif


/**
 * The current runtime plugin API version, packed for the C descriptor ABI.
 */
#define SELENE_RUNTIME_CURRENT_API_VERSION 768

/**
 * A decomposed runtime API version.
 *
 * Plugin descriptors use the packed `SELENE_RUNTIME_CURRENT_API_VERSION`
 * integer rather than this structure.
 */
typedef struct SeleneRuntimeAPIVersion {
  /**
   * Reserved for future use, must be 0.
   */
  uint8_t reserved;
  /**
   * Major version of the API.
   */
  uint8_t major;
  /**
   * Minor version of the API.
   */
  uint8_t minor;
  /**
   * Patch version of the API.
   */
  uint8_t patch;
} SeleneRuntimeAPIVersion;

/**
 * An instance is provided to `selene_runtime_get_next_operations`, which must
 * pass that back to any function it calls in its provided
 * [RuntimeGetOperationInterface].
 */
typedef void *SeleneRuntimeGetOperationInstance;

typedef struct SeleneRuntimeGetOperationInterface {
  void (*measure_fn)(SeleneRuntimeGetOperationInstance,
                     uint64_t,
                     uint64_t);
  void (*measure_leaked_fn)(SeleneRuntimeGetOperationInstance,
                            uint64_t,
                            uint64_t);
  void (*reset_fn)(SeleneRuntimeGetOperationInstance,
                   uint64_t);
  void (*custom_fn)(SeleneRuntimeGetOperationInstance,
                    size_t,
                    const void*,
                    size_t);
  void (*set_batch_time_fn)(SeleneRuntimeGetOperationInstance,
                            uint64_t,
                            uint64_t);
  void (*rzz_fn)(SeleneRuntimeGetOperationInstance,
                 uint64_t,
                 uint64_t,
                 double);
  void (*rxy_fn)(SeleneRuntimeGetOperationInstance,
                 uint64_t,
                 double,
                 double);
  void (*rz_fn)(SeleneRuntimeGetOperationInstance,
                uint64_t,
                double);
  void (*rpp_fn)(SeleneRuntimeGetOperationInstance,
                 uint64_t,
                 uint64_t,
                 double,
                 double);
} SeleneRuntimeGetOperationInterface;

typedef struct RuntimeGetOperationHandle {
  SeleneRuntimeGetOperationInstance instance;
  struct SeleneRuntimeGetOperationInterface interface;
} RuntimeGetOperationHandle;

typedef void *SeleneRuntimeExtractOperationInstance;

typedef struct SeleneRuntimeExtractOperationInterface {
  void (*extract_fn)(SeleneRuntimeExtractOperationInstance,
                     struct RuntimeGetOperationHandle);
} SeleneRuntimeExtractOperationInterface;

typedef struct RuntimeExtractOperationHandle {
  SeleneRuntimeExtractOperationInstance instance;
  struct SeleneRuntimeExtractOperationInterface interface;
} RuntimeExtractOperationHandle;

typedef void *RuntimeInstance;

/**
 * The C ABI descriptor exported by a runtime plugin.
 *
 * Function pointer fields documented as optional may be null. All other
 * function pointer fields must be populated.
 */
typedef struct SeleneRuntimePluginDescriptorV1 {
  /**
   * Must be `sizeof(SeleneRuntimePluginDescriptorV1)`.
   */
  uint64_t struct_size;
  /**
   * Must be `SELENE_RUNTIME_CURRENT_API_VERSION`.
   */
  uint64_t api_version;
  SeleneErrno (*init_fn)(RuntimeInstance *handle,
                         uint64_t n_qubits,
                         uint64_t start,
                         uint32_t argc,
                         const char *const *argv);
  /**
   * Optional. If null, no plugin-specific cleanup is performed.
   */
  SeleneErrno (*exit_fn)(RuntimeInstance handle);
  SeleneErrno (*get_next_operations_fn)(RuntimeInstance handle,
                                        struct RuntimeGetOperationHandle ops);
  SeleneErrno (*shot_start_fn)(RuntimeInstance handle,
                               uint64_t shot_id,
                               uint64_t seed);
  SeleneErrno (*shot_end_fn)(RuntimeInstance handle);
  /**
   * Optional. A null pointer means the plugin exposes no metrics.
   */
  int32_t (*get_metrics_fn)(RuntimeInstance handle,
                            uint8_t nth_metric,
                            char *tag_out,
                            uint8_t *datatype_out,
                            uint64_t *value_out);
  SeleneErrno (*qalloc_fn)(RuntimeInstance handle,
                           uint64_t *qaddress_out);
  SeleneErrno (*qfree_fn)(RuntimeInstance handle,
                          uint64_t qaddress);
  SeleneErrno (*local_barrier_fn)(RuntimeInstance handle,
                                  const uint64_t *qubits,
                                  uint64_t qubits_len,
                                  uint64_t sleep_ns);
  SeleneErrno (*global_barrier_fn)(RuntimeInstance handle,
                                   uint64_t sleep_ns);
  SeleneErrno (*rxy_gate_fn)(RuntimeInstance handle,
                             uint64_t qubit,
                             double theta,
                             double phi);
  SeleneErrno (*rzz_gate_fn)(RuntimeInstance handle,
                             uint64_t qubit0,
                             uint64_t qubit1,
                             double theta);
  SeleneErrno (*rz_gate_fn)(RuntimeInstance handle,
                            uint64_t qubit,
                            double theta);
  SeleneErrno (*rpp_gate_fn)(RuntimeInstance handle,
                             uint64_t qubit0,
                             uint64_t qubit1,
                             double theta,
                             double phi);
  SeleneErrno (*measure_fn)(RuntimeInstance handle,
                            uint64_t qubit,
                            uint64_t *result_id);
  SeleneErrno (*measure_leaked_fn)(RuntimeInstance handle,
                                   uint64_t qubit,
                                   uint64_t *result_id);
  SeleneErrno (*reset_fn)(RuntimeInstance handle,
                          uint64_t qubit);
  SeleneErrno (*force_result_fn)(RuntimeInstance handle,
                                 uint64_t result_id);
  SeleneErrno (*get_bool_result_fn)(RuntimeInstance handle,
                                    uint64_t id,
                                    int8_t *result);
  SeleneErrno (*get_u64_result_fn)(RuntimeInstance handle,
                                   uint64_t id,
                                   uint64_t *result);
  SeleneErrno (*set_bool_result_fn)(RuntimeInstance handle,
                                    uint64_t result_id,
                                    bool result);
  SeleneErrno (*set_u64_result_fn)(RuntimeInstance handle,
                                   uint64_t result_id,
                                   uint64_t result);
  SeleneErrno (*increment_future_refcount_fn)(RuntimeInstance handle,
                                              uint64_t result_id);
  SeleneErrno (*decrement_future_refcount_fn)(RuntimeInstance handle,
                                              uint64_t result_id);
  /**
   * Optional. A null pointer means custom calls are unsupported.
   */
  SeleneErrno (*custom_call_fn)(RuntimeInstance handle,
                                uint64_t tag,
                                const void *data,
                                size_t data_len,
                                uint64_t *result);
  /**
   * Optional. A null pointer means simulated delays are unsupported.
   */
  SeleneErrno (*simulate_delay_fn)(RuntimeInstance handle,
                                   uint64_t delay_ns);
} SeleneRuntimePluginDescriptorV1;

#endif  /* SELENE_RUNTIME_H */
